version: '3.9'
services:
  mongodb:
    image: mongo:latest
    container_name: mongo
    restart: unless-stopped
    environment:
      - MONGO_INITDB_DATABASE=rtis_db_dev
      - MONGO_INITDB_ROOT_USERNAME=rtisadmin
      - MONGO_INITDB_ROOT_PASSWORD=rtisPassword
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

  # portainer:
  #     image: portainer/portainer-ce
  #     container_name: portainer
  #     restart: always
  #     ports:
  #         - 9000:9000
  #     volumes:
  #         - /var/run/docker.sock:/var/run/docker.sock
  #         - portainer_data:/data

volumes:
  mongodb_data_container:
  # portainer_data:
